version: "3.9"
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        build:
            context: ./infra/mysql
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
            - ${LOG_DIR_MYSQL}:/var/log/mysql
            - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/my.cnf
            - ${MYSQL_DUMP_DIR}:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MY_DATABASE}
        ports:
            - "3307:3306"
        networks:
            - conversa-network
    conversa-api:
        depends_on:
            -   mysql
        image: yacinerafes/conversaapi:latest
        container_name: conversa-api
        ports:
            - "8080:8080"
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_NAME=${MY_DATABASE}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - conversa-network
    conversa-web:
        image: yacinerafes/conversaweb:latest
        container_name: conversa-web
        ports:
            - "8090:8080"
        depends_on:
            - conversa-api
        networks:
            - conversa-network

networks:
    conversa-network:
        driver: bridge

volumes:
    maven_repo: