name: conversa
services:
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        build:
            context: ./infra/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MY_DATABASE}
        ports:
            - "3307:3306"
    conversa-api:
        depends_on:
            -   mysql
        image: yacinerafes/conversaapi:latest
        build:
            context: ./ConversaAPI
        container_name: conversa-api
        ports:
            - "8080:8080"
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_NAME=${MY_DATABASE}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
    conversa-web:
        image: yacinerafes/conversaweb:latest
        container_name: conversa-web
        build:
            context: ./ConversaWeb
        ports:
            - "8090:8080"